# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Device-Blkid
version:      0.9.1
version_from: lib/Device/Blkid.pm
installdirs:  site
requires:
    Exporter:                      0
    Test::Builder:                 0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
